[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "1"

[[bin]]
name = "1plus"

[[bin]]
name = "2"

[dependencies]
regex = "1.10.2"
